type: class
title: Configuration model
include_relations_also_as_members: true
glob:
  - src/config/config.cc
include:
  namespaces:
    - clanguml::config
  context:
    - clanguml::config::inheritable_diagram_options
    - clanguml::config::config
    - clanguml::config::diagram
exclude:
  elements:
    - r: "clanguml::config::option<.*>"
using_namespace:
  - clanguml::config
plantuml:
  after:
    - 'note left of {{ alias("inheritable_diagram_options") }}: Options common to all diagram types.'
    - 'note right of {{ alias("config") }}: General options not used by diagrams.'
    - 'note bottom of {{ alias("class_diagram") }}: Options for specific class diagrams'
    - 'note bottom of {{ alias("sequence_diagram") }}: Options for specific sequence diagrams'
    - 'note bottom of {{ alias("package_diagram") }}: Options for specific package diagrams'
    - 'note bottom of {{ alias("include_diagram") }}: Options for specific include diagrams'
