type: class
title: clanguml::config::config context diagram
include_relations_also_as_members: true
glob:
  - src/config/config.cc
include:
  namespaces:
    - clanguml::config
  context:
    - clanguml::config::config
using_namespace:
  - clanguml::config