type: sequence
title: Configuration file loading sequence diagram
combine_free_functions_into_file_participants: true
generate_method_arguments: none
generate_condition_statements: true
generate_message_comments: true
glob:
  - src/config/config.cc
  - src/config/yaml_decoders.cc
include:
  namespaces:
    - clanguml
    - YAML
exclude:
  elements:
    - r: "clanguml::config::option.*"
  paths:
    - src/util/util.h
using_namespace:
  - clanguml
from:
  - function: "clanguml::config::load(const std::string &,bool,std::optional<bool>,std::optional<bool>,bool)"
